version: '3.9'

services:
  floppa_bot_tests:
    container_name: floppa_bot_tests
    build:
      context: .
      dockerfile: docker/Dockerfile-test
    depends_on:
      - mongo_db_tests
    env_file:
      - .env
    networks:
      test_floppa_net:
    #links:
    #  - "mongo_db_tests:mongo_db"

  mongo_db_tests:
    image: 'mongo:4.2.6'
    command: "--logpath=/dev/null"
    ports:
      - '27017:21017'
    volumes:
      - ./storage/debug/mongo:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    networks:
      test_floppa_net:

networks:
  test_floppa_net:
    driver: bridge
