version: '3.9'

services:
  floppa_bot:
    container_name: floppa_bot
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - mongo_db
    env_file:
      - .env
    restart: always
    networks:
      floppa_net:

  mongo_db:
    container_name: ${MONGO_HOST}
    image: 'mongo:4.2.21'
    ports:
      - '27017:27017'
    volumes:
      - ./storage/mongo:/data/db:rw
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    restart: unless-stopped
    networks:
      floppa_net:

networks:
  floppa_net:
    driver: bridge
